name: newsappflutter
description: newsappflutter.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.1
  lint: ^2.3.0
  webview_flutter: ^3.0.4
  flutter_riverpod: ^2.3.6
  google_generative_ai: ^0.2.2
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.30.0
  firebase_storage: ^11.7.2
  flutter_pdfview: ^1.2.7



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/download.jpeg"

flutter:
  uses-material-design: true
